/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nomeda' at '12/30/16 6:22 PM' with Gradle 3.2.1
 *
 * @author nomeda, @date 12/30/16 6:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
